---
micronaut:
  application:
    name: churripuntos-api

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
